# Generated by Django 5.2.5 on 2025-09-13 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0008_alter_purchase_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('file_purpose', models.CharField(choices=[('profile_picture', 'PROFILE_PICTURE'), ('film_poster', 'FILM_POSTER'), ('trailer', 'TRAILER'), ('teaser', 'TEASER'), ('snippet', 'SNIPPET'), ('main_file', 'MAIN_FILE'), ('others', 'OTHERS')], max_length=100, verbose_name='File purpose')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Content')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='File MIME Type')),
                ('is_verified', models.BooleanField(blank=True, default=False, verbose_name='Is this file verified')),
                ('upload_session_id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, verbose_name='File Upload Session ID')),
                ('currently_under_processing', models.BooleanField(blank=True, default=True, verbose_name='Is this file currently under processing')),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=500, null=True, verbose_name='Original File Name')),
                ('film', models.ForeignKey(blank=True, help_text='The film related to the file', null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.feed', verbose_name='File Film')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='File Owner')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
