# Generated by Django 5.2.5 on 2025-10-01 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0003_remove_filemodel_file_alter_filemodel_film_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('source_key', models.CharField(max_length=1024, verbose_name='File Source Key')),
                ('source_checksum', models.CharField(blank=True, help_text='checksum generated by client during file upload', max_length=128, null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('running', 'RUNNING'), ('failed', 'FAILED'), ('completed', 'COMPLETED')], default='pending', help_text='The status of the file processing job', max_length=32)),
                ('current_stage', models.CharField(blank=True, choices=[('checksum', 'CHECKSUM'), ('probe', 'PROBE'), ('validate', 'VALIDATE'), ('transcode', 'TRANSCODE'), ('package_hls', 'PACKAGE_HLS'), ('package_dash', 'PACKAGE_DASH'), ('thumbnails', 'THUMBNAILS'), ('audio', 'AUDIO'), ('finalize', 'FINALIZE')], help_text='The current stage of the file processing job', max_length=64, null=True)),
                ('stages', models.JSONField(blank=True, default=dict, null=True, verbose_name='Per stage details')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='ffprobe result and extracted fields data', null=True)),
                ('renditions', models.JSONField(blank=True, default=dict, help_text='list of produced renditions (keys, sizes e.t.c)', null=True)),
                ('packaging', models.JSONField(blank=True, default=dict, help_text='hls and dash packaging results', null=True)),
                ('thumbnails', models.JSONField(blank=True, default=dict, help_text='list of thumbnail keys', null=True)),
                ('audio', models.JSONField(blank=True, default=dict, help_text='audio related outputs', null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='file_storage.filemodel', verbose_name='File Being Processed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Processing Job',
                'verbose_name_plural': 'File Processing Jobs',
            },
        ),
    ]
