# Generated by Django 5.2.5 on 2025-10-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0004_fileprocessingjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='currently_under_processing',
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='upload_session_id',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='checksum',
            field=models.CharField(blank=True, help_text='checksum for file integrity verification', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='dash_mpd_key',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Dash MPD Key'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height of File'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Width of File'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='format_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Format Name'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='has_audio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='hls_master_key',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='HLS Master Key'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='last_error',
            field=models.TextField(blank=True, null=True, verbose_name='Last Error During Processing'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('running', 'RUNNING'), ('failed', 'FAILED'), ('completed', 'COMPLETED')], default='pending', max_length=16, verbose_name='Processing Status'),
        ),
    ]
