# Generated by Django 5.1.1 on 2024-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_pin',
            field=models.IntegerField(),
        ),
    ]
