# Generated by Django 5.1.1 on 2024-10-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_wallet_account_number_alter_wallet_wallet_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
