# Generated by Django 5.2.5 on 2025-10-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Virtual Account Number'),
        ),
    ]
