# Generated by Django 5.2.5 on 2025-11-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_virtual_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='creation_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('failed', 'FAILED'), ('completed', 'COMPLETED')], default='pending', max_length=20, verbose_name='Wallet Creation Status'),
        ),
    ]
