# Generated by Django 5.2.5 on 2026-02-17 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_rename_balance_wallet_earnings_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('funding_balance__gte', 0)), name='funding_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('earnings_balance__gte', 0)), name='earnings_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('total_balance__gte', 0)), name='total_balance_non_negative'),
        ),
    ]
