# Generated by Django 4.2.4 on 2024-10-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_transaction_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient_account_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient_bank',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient_name',
            field=models.CharField(max_length=225),
        ),
    ]
