# Generated by Django 4.2.4 on 2024-10-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_transaction_recipient_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('internal', 'internal'), ('external', 'external')], max_length=50, null=True),
        ),
    ]
