# Generated by Django 5.1.1 on 2024-10-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_wallet_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='account_number',
            new_name='wallet_number',
        ),
    ]
