# Generated by Django 5.2.5 on 2025-08-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_usersession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
