# Generated by Django 5.2.5 on 2025-08-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_user_has_pending_issues_user_is_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is user a film creator?'),
        ),
    ]
