# Generated by Django 5.2.5 on 2025-08-19 20:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=225, verbose_name='Film Title')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated slug', max_length=255, verbose_name='Slug')),
                ('plot', models.TextField(help_text='A quick plot of the film', verbose_name='Film Plot')),
                ('genre', models.CharField(choices=[('Action', 'ACTION'), ('Drama', 'DRAMA'), ('Romance', 'ROMANCE'), ('Horror', 'HORROR'), ('Sci-Fi', 'SCI_FI'), ('Fantasy', 'FANTASY'), ('Thriller', 'THRILLER'), ('Comedy', 'COMEDY')], help_text='The genre that the film falls under', max_length=100, verbose_name='Film Genre')),
                ('type', models.CharField(choices=[('standalone', 'STANDALONE'), ('series', 'SERIES'), ('documentary', 'DOCUMENTARY'), ('short film', 'SHORT_FILM'), ('franchise', 'FRANCHISE')], help_text='The type of film e.g Series, Standalone', max_length=100, verbose_name='Film Type')),
                ('length', models.TimeField(blank=True, verbose_name='Film Length')),
                ('cast', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text='List of the names of major actors from the film', size=None, verbose_name='Film Actors')),
                ('crew', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of the names of film crew members', null=True, size=None, verbose_name='Film Crew')),
                ('language', models.CharField(default='en', help_text="Language of the movie, e.g., 'en' for English", max_length=2, verbose_name='Language')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to=settings.AUTH_USER_MODEL, verbose_name='Owned By')),
                ('saved', models.ManyToManyField(blank=True, related_name='bookmarked_films', to=settings.AUTH_USER_MODEL, verbose_name='Users Who Have Bookmarked the film')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
    ]
