# Generated by Django 5.2.5 on 2025-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_feed_length'),
    ]

    
    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="crew",
        ),
        migrations.AddField(
            model_name="feed",
            name="crew",
            field=models.JSONField(default=dict), 
        ),
    ]
