# Generated by Django 5.2.5 on 2025-08-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_feed_release_date_alter_feed_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='is_released',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Has the movie been released?'),
        ),
    ]
