# Generated by Django 5.2.5 on 2025-09-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_feed_rental_duration_feed_sale_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Film Purchase', 'verbose_name_plural': 'Film Purchases'},
        ),
    ]
