# Generated by Django 5.2.5 on 2025-10-11 13:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_alter_feed_film_file'),
        ('file_storage', '0005_remove_filemodel_currently_under_processing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=225, verbose_name='Short Title')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated slug', max_length=255, verbose_name='Slug')),
                ('type', models.CharField(choices=[('trailer', 'TRAILER'), ('teaser', 'TEASER'), ('snippet', 'SNIPPET')], max_length=50, verbose_name='Short Type')),
                ('caption', models.TextField(blank=True, help_text='A short caption for the short', verbose_name='Caption')),
                ('length', models.DurationField(blank=True, null=True, verbose_name='Short Length (Runtime)')),
                ('language', models.CharField(default='en', help_text="Language code, e.g., 'en' for English", max_length=2, verbose_name='Language')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Optional list of tags for discovery', size=None)),
                ('release_date', models.DateField(blank=True, help_text='The date this short was/will be released', null=True, verbose_name='Release Date')),
                ('is_released', models.BooleanField(blank=True, default=False, null=True, verbose_name='Has the short been released?')),
                ('views_count', models.BigIntegerField(default=0)),
                ('likes_count', models.BigIntegerField(default=0)),
                ('comments_count', models.BigIntegerField(default=0)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short', to='file_storage.filemodel', verbose_name='Short Media File')),
                ('film', models.ForeignKey(help_text='Film this short is related to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shorts', to='feed.feed', verbose_name='Film')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_shorts', to=settings.AUTH_USER_MODEL, verbose_name='Owned By')),
                ('saved', models.ManyToManyField(blank=True, related_name='bookmarked_shorts', to=settings.AUTH_USER_MODEL, verbose_name='Users Who Have Bookmarked this short')),
            ],
            options={
                'verbose_name': 'Short',
                'verbose_name_plural': 'Shorts',
            },
        ),
    ]
