# Generated by Django 5.2.5 on 2025-10-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='film_file',
        ),
    ]
