# Generated by Django 5.2.5 on 2025-10-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_remove_feed_film_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='length',
        ),
        migrations.RemoveField(
            model_name='short',
            name='length',
        ),
        migrations.RemoveField(
            model_name='short',
            name='title',
        ),
        migrations.AddField(
            model_name='feed',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Film duration(Runtime)'),
        ),
        migrations.AddField(
            model_name='short',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Short Duration (Runtime)'),
        ),
    ]
