# Generated by Cursor on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0015_alter_purchase_payment_status_alter_purchase_status"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE feed_purchase
                    ALTER COLUMN expiry_time TYPE timestamp with time zone
                    USING (
                        CASE
                            WHEN expiry_time IS NULL THEN NULL
                            ELSE (CURRENT_DATE + expiry_time) AT TIME ZONE 'UTC'
                        END
                    );
                    """,
                    reverse_sql="""
                    ALTER TABLE feed_purchase
                    ALTER COLUMN expiry_time TYPE time without time zone
                    USING (
                        CASE WHEN expiry_time IS NULL THEN NULL ELSE expiry_time::time END
                    );
                    """,
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="purchase",
                    name="expiry_time",
                    field=models.DateTimeField(
                        blank=True,
                        help_text="Date and time the rental access expires (for rented films)",
                        null=True,
                        verbose_name="Expiry Time",
                    ),
                )
            ],
        ),
    ]
