# Generated by Django 5.2.5 on 2026-03-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_feed_genre_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='method',
            field=models.CharField(blank=True, choices=[('bank_charge', 'BANK_CHARGE'), ('transfer', 'TRANSFER')], null=True, verbose_name='Purchase Method'),
        ),
    ]
