# Generated by Django 5.2.5 on 2025-08-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_transaction_flw_transfer_id_alter_transaction_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
