# Generated by Django 5.2.5 on 2025-11-08 09:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0010_delete_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=15, unique=True, verbose_name='Transaction Reference')),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Initiated', 'INITIATED'), ('Completed', 'COMPLETED'), ('Failed', 'FAILED'), ('Cancelled', 'CANCELLED'), ('Reversed', 'REVERSED')], default='Pending', max_length=20, verbose_name='Transaction Status')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3, verbose_name='currency')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date and Time the transaction was marked as completed', null=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('user wallet', 'USER_WALLET'), ('provider wallet', 'PROVIDER_WALLET'), ('sales fee', 'SALES_FEE'), ('external funding & withdrawal', 'EXTERNAL_FUNDING_WITHDRAWAL'), ('external payment', 'EXTERNAL_PAYMENT')], max_length=50, verbose_name='Ledger Account Type')),
                ('currency', models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3, verbose_name='currency')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Ledger Account Owner')),
            ],
            options={
                'verbose_name': 'Ledger Account',
                'verbose_name_plural': 'Ledger Accounts',
                'unique_together': {('owner', 'type', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='LedgerJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='journal', to='payment.transaction')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('Credit', 'CREDIT'), ('Debit', 'DEBIT')], verbose_name='Entry Type')),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Completed', 'COMPLETED'), ('Failed', 'FAILED')], default='Pending', verbose_name='Entry Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Entry Amount')),
                ('entered_at', models.DateTimeField(blank=True, help_text='Date and Time the entry was entered', null=True)),
                ('account', models.ForeignKey(help_text='Ledger account that the money was moved out of or into', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payment.ledgeraccount')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payment.ledgerjournal')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'unique_together': {('journal', 'line_no')},
            },
        ),
    ]
