# Generated by Django 5.2.5 on 2026-02-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_remove_journalentry_entered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='transaction',
            name='failed_at',
            field=models.DateTimeField(blank=True, help_text='Date and Time the transaction was marked as failed', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('payment', 'PAYOUT'), ('purchase', 'PURCHASE'), ('funding', 'FUNDING')], help_text='The purpose of the transaction(funding, purchase, payout)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='successful_at',
            field=models.DateTimeField(blank=True, help_text='Date and Time the transaction was marked as successful', null=True),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='type',
            field=models.CharField(choices=[('user wallet', 'USER_WALLET'), ('provider wallet', 'PROVIDER_WALLET'), ('sales fee', 'SALES_FEE'), ('funding', 'FUNDING'), ('withdrawal', 'WITHDRAWAL'), ('external payment', 'EXTERNAL_PAYMENT')], max_length=50, verbose_name='Ledger Account Type'),
        ),
    ]
