# Generated by Django 5.2.5 on 2026-04-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0014_remove_transaction_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="finalisation_state",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("success_finalised", "SUCCESS_FINALISED"),
                    ("failed_finalised", "FAILED_FINALISED"),
                    ("success_not_finalised", "SUCCESS_NOT_FINALISED"),
                    ("failed_not_finalised", "FAILED_NOT_FINALISED"),
                    ("refund_required", "REFUND_REQUIRED"),
                    ("refund_pending", "REFUND_PENDING"),
                    ("refund_failed", "REFUND_FAILED"),
                ],
                default="pending",
                max_length=30,
                verbose_name="Transaction Finalisation State",
            ),
        ),
    ]
