# Generated by Django 5.2.5 on 2025-10-13 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('processing_complete', 'PROCESSING_COMPLETE'), ('processing_failed', 'PROCESSING_FAILED')], help_text='The event that triggers this webhook', max_length=64, verbose_name='Webhook Event')),
                ('target_url', models.URLField(max_length=1024, verbose_name='Target URL')),
                ('secret_encrypted', models.TextField(help_text='Encrypted secret for verification by client', verbose_name='Encrypted Secret')),
                ('is_active', models.BooleanField(default=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_response_code', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, help_text='The owner of this webhook endpoint, null if global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to=settings.AUTH_USER_MODEL, verbose_name='Webhook Endpoint Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
