# Generated by Django 5.2.5 on 2025-10-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='secret_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted secret for verification by client', verbose_name='Encrypted Secret'),
        ),
    ]
