# Generated by Django 5.2.5 on 2025-10-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_alter_webhookendpoint_secret_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='event',
            field=models.CharField(choices=[('processing_complete', 'PROCESSING_COMPLETED'), ('processing_failed', 'PROCESSING_FAILED')], help_text='The event that triggers this webhook', max_length=64, verbose_name='Webhook Event'),
        ),
    ]
