# Generated by Django 5.2.5 on 2025-11-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_alter_webhookendpoint_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='event',
            field=models.CharField(choices=[('processing_complete', 'PROCESSING_COMPLETED'), ('processing_failed', 'PROCESSING_FAILED'), ('wallet_creation_completed', 'WALLET_CREATION_COMPLETED'), ('wallet_creation_failed', 'WALLET_CREATION_FAILED'), ('funding_completed', 'FUNDING_COMPLETED'), ('funding_failed', 'FUNDING_FAILED'), ('bank_charge_initiated', 'BANK_CHARGE_INITIATED'), ('bank_charge_initiation_failed', 'BANK_CHARGE_INITIATION_FAILED')], help_text='The event that triggers this webhook', max_length=64, verbose_name='Webhook Event'),
        ),
    ]
