# Generated by Django 5.2.5 on 2026-03-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhook", "0005_alter_webhookendpoint_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebhookEndpoint",
        ),
    ]
