# Generated by Django 5.2.5 on 2026-04-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhook", "0006_delete_webhookendpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_last_modified", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("flutterwave", "FLUTTERWAVE")], max_length=30
                    ),
                ),
                ("event", models.CharField(max_length=60)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                (
                    "tx_ref",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "provider_event_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("handler_response", models.JSONField(blank=True, default=dict)),
                (
                    "processing_state",
                    models.CharField(
                        choices=[
                            ("received", "RECEIVED"),
                            ("acknowledged", "ACKNOWLEDGED"),
                            ("ignored", "IGNORED"),
                            ("failed", "FAILED"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-date_added"]},
        ),
    ]
